import os
import requests
from moviepy.editor import VideoFileClip, AudioFileClip
import google.oauth2.credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# Saari API Keys
PEXELS_KEY = os.environ.get('PEXELS_API_KEY')
ELEVENLABS_KEY = os.environ.get('ELEVENLABS_API_KEY')
CLIENT_ID = os.environ.get('CLIENT_ID')
CLIENT_SECRET = os.environ.get('CLIENT_SECRET')
REFRESH_TOKEN = os.environ.get('REFRESH_TOKEN')

def generate_audio(text, filename="audio.mp3"):
    url = "https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM"
    headers = {"xi-api-key": ELEVENLABS_KEY, "Content-Type": "application/json"}
    data = {"text": text, "model_id": "eleven_monolingual_v1"}
    response = requests.post(url, json=data, headers=headers)
    with open(filename, "wb") as f:
        f.write(response.content)
    return filename

def download_video(query, filename="bg_video.mp4"):
    headers = {"Authorization": PEXELS_KEY}
    url = f"https://api.pexels.com/videos/search?query={query}&per_page=1&orientation=portrait"
    response = requests.get(url, headers=headers).json()
    video_url = response['videos'][0]['video_files'][0]['link']
    
    r = requests.get(video_url, stream=True)
    with open(filename, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024):
            if chunk: f.write(chunk)
    return filename

def create_final_video():
    audio_path = generate_audio("Hello! Welcome to our channel. Today we have amazing facts for you!")
    video_path = download_video("nature")
    
    video = VideoFileClip(video_path)
    audio = AudioFileClip(audio_path)
    final_video = video.set_audio(audio).subclip(0, audio.duration)
    final_video.write_videofile("final_video.mp4", fps=24, codec="libx264", audio_codec="aac")
    return "final_video.mp4"

def upload_to_youtube(video_file):
    credentials = google.oauth2.credentials.Credentials(
        None, refresh_token=REFRESH_TOKEN, token_uri="https://oauth2.googleapis.com/token",
        client_id=CLIENT_ID, client_secret=CLIENT_SECRET
    )
    youtube = build('youtube', 'v3', credentials=credentials)
    body = {
        'snippet': {'title': 'Daily Automated Shorts', 'description': 'Auto generated by AI', 'tags': ['Shorts', 'AI'], 'categoryId': '22'},
        'status': {'privacyStatus': 'public'}
    }
    media = MediaFileUpload(video_file, chunksize=-1, resumable=True)
    youtube.videos().insert(part=','.join(body.keys()), body=body, media_body=media).execute()

if __name__ == '__main__':
    final_clip = create_final_video()
    upload_to_youtube(final_clip)
