name: Run YouTube Automation

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Video Editor and Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install requests moviepy==1.0.3 google-api-python-client google-auth-oauthlib google-auth-httplib2

    - name: Run Auto Video Creator
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: python upload.py
